# QuickBind Combined Configuration File
name: 'quickbind_default'
seed: 1

# Input Embeddings Configuration
input_embed:
  aa_feat: 21                 
  lig_atom_feat: 44           
  c_emb: 32                   
  c_s: 64                     
  c_z: 64                     
  use_op_edge_embed: false    
  use_pairwise_dist: true     
  use_radial_basis: false     
  use_rel_pos: true           
  use_multimer_rel_pos: false 
  mask_off_diagonal: true     
  one_hot_adj: false          
  use_topological_distance: false  

# Evoformer Configuration
evoformer:
  c_hidden_msa_att: 16      
  c_hidden_opm: 16          
  c_hidden_mul: 64          
  c_hidden_pair_att: 16     
  c_s_out: 64               
  no_heads_msa: 8           
  no_heads_pair: 4          
  no_evo_blocks: 12         
  transition_n: 4           
  msa_dropout: 0.15         
  pair_dropout: 0.25        
  opm_first: false          
  chunk_size: null          
  use_full_evo_stack: true  

# Structure Module Configuration
structure:
  c_hidden: 16
  no_heads: 12
  no_qk_points: 4
  no_v_points: 8
  num_struct_blocks: 8
  dropout_rate: 0.1
  no_transition_layers: 1
  share_ipa_weights: true
  use_gated_ipa: true
  communicate: false
  sum_pool: false
  mean_pool: false
  att_update: true
  construct_frames: true
  blackhole_init: false

# Recycling Configuration
recycling:
  recycle: false             
  recycle_iters: 1           

# Auxiliary Heads Configuration
aux_heads:
  use_aux_head: true
  use_lig_aux_head: true
  no_dist_bins: 64
  no_dist_bins_lig: 42
  output_s: false

# Loss Function Configuration
loss:
  lig_lig_loss_weight: 1.0
  lig_rec_loss_weight: 1.0
  aux_loss_weight: 1.0
  steric_clash_loss_weight: 1.0  
  full_distogram_loss_weight: 0.0
  clamp_distance: 10.0
  eps: 1.0e-8

# Training Configuration
training:
  num_epochs: 500
  batch_size: 1
  patience: 50
  iters_to_accumulate: 2
  optimizer: AdamW
  lr: 1.0e-4
  weight_decay: 1.0e-4
  clip_grad: 100

# Dataset Configuration
dataset:
  train_names: 'data/timesplit_no_lig_overlap_train
  val_names: 'data/timesplit_no_lig_overlap_val'
  test_names: 'data/timesplit_test'
  num_workers: 4
  chain_radius: 10
  remove_h: true
  cropping: true
  crop_size: 256
  binding_site_cropping: true
  recenter: true

# Logging Configuration
logging:
  wandb:
    project: 'QuickBind'
    resume: allow